### ISSUE TITLE
AttributeError: 'list' object has no attribute 'copy'

### ISSUE THREAD

**Issue by spmuppar** [zingale/pyro2#24]
I'm getting this error when trying to simulate the advection for advection_rk,fv4,weno solvers.

File "/home/administrator/Downloads/pyro2-master/mesh/patch.py", line 848, in cell_center_data_clone
    new.derives = old.derives.copy()
AttributeError: 'list' object has no attribute 'copy'

I changed the "**old.derives.copy()**" to just "**old.derives**" the solver ran normally.

I'm using pyro2 in python 2.7 environment.

**Comment by zingale** [comment]
this is a python 2 issue.  In python 3, lists have a `copy()` method.  We can work around this, but we really are not supporting python 2 anymore -- all the testing is done using python 3, so I am not sure whether python 2 really gives correct answers anymore (I think the WENO code will not, for example).

Is it possible to use python 3?

**Comment by spmuppar** [comment]
Yes, I can use python 3.
Thanks.
