### ISSUE TITLE
y-velocity and energy are same just before plotting

### ISSUE THREAD

**Issue by spmuppar** [zingale/pyro2#25]
Pardon me if this is silly, 
If I place a breakpoint just before line 284 in simulation.py of compressible solver, to check the variables u, v, p, rho, e..
the arrays of v and energy are same values. 

And also ivars.iu = ivars.iener = 1

**Comment by zingale** [comment]
I am not sure I understand your first comment.

For the second, you are mixing up the integer indices used for the conserved and primitive variable vectors.  For conserved variables, they are: `ivars.idens`, `ivars,ixmom`, ivars.iymom`, and `ivars.iener`.
The ordering doesn't really matter, but it is defined by the order in which they were registered in the `initialized()` method in the `Simulation` class.  In this case, energy is the second variable, so `ivars.iener = 1`.

For the primitive variable state, the indices are: `ivars.irho`, `ivars.iu`, `ivars.iv`, `ivars.ip`, and in that order.

You are usually dealing with a state of conserved variables or primitive variables, not a mix of the two, so you need to use the correct set of indices depending on what the state is.

**Comment by spmuppar** [comment]
perfect, understood
