### ISSUE TITLE
Multigrid projection docs

### ISSUE THREAD

**Issue by IanHawke** [zingale/pyro2#33]
The sphinx docs (`multigrid_basics.rst`) have a `projection` example that is missing a figure. It is meant to be the output of `project-periodic.py`, but that script is also missing. 

There is [this script](https://github.com/zingale/hydro_examples/blob/master/incompressible/project.py) in your `hydro_examples` repo, but I'm not sure it's doing the same thing?

**Comment by zingale** [comment]
ah... it looks like I moved that script into the `examples/` directory.  I think I did this to prevent these examples from being picked up by the API doc-ing from sphinx.  Might not be the most elegant solution.  I'll fix the docs.

**Comment by zingale** [comment]
this should be fixed now

**Comment by IanHawke** [comment]
Great: looks good, thanks.
