### ISSUE TITLE
improve energy conservation with gravity

### ISSUE THREAD

**Issue by BenWibking** [zingale/pyro2#5]
Energy conservation with body forces can be substantially improved if the mass fluxes are used, instead of the cell-centered estimates of the work.  For general body forces, I have tested:

```
       energy_update  = 0.5*dtdy*(Flux_y.v(n=self.vars.idens) + Flux_y.jp(1,n=self.vars.idens)) * \
                         0.5*(old_yacc_src.v() + yacc_src.v())*myg.dy

        energy_update += 0.5*dtdx*(Flux_x.v(n=self.vars.idens) + Flux_x.ip(1,n=self.vars.idens)) * \
                         0.5*(old_xacc_src.v() + xacc_src.v())*myg.dx

        ener.v()[:,:] += energy_update
```

This is identical to the formulation in Springel 2010 (the Arepo paper).

I also switched the half-step prediction using the primitive variables:

```
    V_l[1:,:,vars.iu] += 0.5*dt*0.5*(xacc_src.d[0:-1,:]+xacc_src.d[1:,:])
    V_l[1:,:,vars.iv] += 0.5*dt*0.5*(yacc_src.d[0:-1,:]+yacc_src.d[1:,:])

    V_r[1:-1,:,vars.iu] += 0.5*dt*0.5*(xacc_src.d[2:,:]+xacc_src.d[1:-1,:])
    V_r[1:-1,:,vars.iv] += 0.5*dt*0.5*(yacc_src.d[2:,:]+yacc_src.d[1:-1,:])
```

and likewise for the y-direction.  This seems to work well, though there may be a better way to do the indexing for the half-step variables.

**Comment by zingale** [comment]
this approach is done in Castro now.  As pyro is not meant to be a research
code, I opted for simplicity here.

On Mon, Nov 30, 2015 at 9:56 AM, Ben Wibking <notifications@github.com>
wrote:

> Energy conservation with body forces can be substantially improved if the
> mass fluxes are used, instead of the cell-centered estimates of the work.
> For general body forces, I have tested:
>
>        energy_update  = 0.5*dtdy*(Flux_y.v(n=self.vars.idens) + Flux_y.jp(1,n=self.vars.idens)) * \
>                          0.5*(old_yacc_src.v() + yacc_src.v())*myg.dy
>
>         energy_update += 0.5*dtdx*(Flux_x.v(n=self.vars.idens) + Flux_x.ip(1,n=self.vars.idens)) * \
>                          0.5*(old_xacc_src.v() + xacc_src.v())*myg.dx
>
>         ener.v()[:,:] += energy_update
>
> This is identical to the formulation in Springel 2010 (the Arepo paper).
>
> I also switched the half-step prediction using the primitive variables:
>
>     V_l[1:,:,vars.iu] += 0.5*dt*0.5*(xacc_src.d[0:-1,:]+xacc_src.d[1:,:])
>     V_l[1:,:,vars.iv] += 0.5*dt*0.5*(yacc_src.d[0:-1,:]+yacc_src.d[1:,:])
>
>     V_r[1:-1,:,vars.iu] += 0.5*dt*0.5*(xacc_src.d[2:,:]+xacc_src.d[1:-1,:])
>     V_r[1:-1,:,vars.iv] += 0.5*dt*0.5*(yacc_src.d[2:,:]+yacc_src.d[1:-1,:])
> ``
> and likewise for the y-direction.  This seems to work well, though there may be a better way to do the indexing for the half-step variables.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zingale/pyro2/issues/5>.
>



-- 
Michael Zingale
Associate Professor

Dept. of Physics & Astronomy • Stony Brook University • Stony Brook, NY
11794-3800
*phone*:  631-632-8225
*e-mail*: Michael.Zingale@stonybrook.edu
*web*: http://www.astro.sunysb.edu/mzingale
github: http://github.com/zingale

**Comment by BenWibking** [comment]
That is good to know. It is not apparent from the documentation. It is much easier to learn the state-of-the-art techniques if I only have to read through thousands of lines of source code, rather than tens of thousands of lines!
