### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by zingale** [zingale/pyro2#7]
Need to better document the flow of the code, including:

  -- how to add custom BCs
  -- how to add solvers
  -- how to add new problems

**Comment by astroboylrx** [comment]
I'm using pyro2 with TkAgg backend. However, interactive plotting doesn't work. More specifically, `plt.figure()` successfully create a window, but nothing shows up in it, and then the window exits after the program ends. This issue happens on both Ubuntu 16.04 and Mac OS 10.11. With some googling, I put `plt.pause(0.0001)` after each `sim.dovis()` in pyro.py, which fixes the issue. But the official documentation of `pause` function does not give a reasonable explanation. Additionally, by using `plt.pause(0.0001)`, I find the interactive plotting now even works with the "MacOSX" and "Qt5Agg" backends. I think this workaround might be useful to someone, so I comment here.

**Comment by zingale** [comment]
indeed, I see this now, it seems to be related to matplotlib 1.5 -- I just upgraded and get that error.  I'll add pauses
